### PR TITLE
add tutorial: Adding Twitter sign in to your Node.js + Express web application using OAuth

### PR DESCRIPTION
**Pull request by sixhobbits**

### CODE REVIEW

**Comment by sixhobbits** [comment]
@mooreds - not sure how cover images are handled exactly? Let me know if we should create one and if you have any guidelines for them.

**Comment by mooreds** [comment]
Cover images are handled by us, thanks! @sixhobbits

**Comment by mooreds** [comment]
Comments: 

* I didn't see logout, can we add that? You will need to destroy the express session. Here's an example: https://github.com/FusionAuth/fusionauth-example-node/blob/master/routes/index.js
* I didn't see the github repository (link 404ed). Can you please share that with me?

Thanks!

**Comment by sixhobbits** [comment]
@mooreds - thanks we'll add logout. Here's the repo that needs to be forked https://github.com/ritza-co/fusionauth-example-express-twitter

**Comment by mooreds** [comment]
Superseded by https://github.com/FusionAuth/fusionauth-site/pull/1717

**Pull request closed without merging**
