### PR TITLE
Make vale work

### PR DESCRIPTION
**Pull request by mooreds**
* made vale fail on error
* fixed a ton of misspellings or incorrect casing
* wrote ignore clauses for some more cases
* updated dev docs to reflect new vale work
* fixed incorrect example apps count

### CODE REVIEW

**Comment by lyleschemmerling** [comment]
how were you testing the updates? Just letting the github action run on commit, or are you running this locally?

**Comment by mooreds** [comment]
Running locally. Per devdocsreadme, you can run with `vale --config .vale.ini  astro/src/content` or a more narrowly focused path. That is if you have installed vale locally, which I have. I think there's also a way to run it via docker if you don't want to install it.

**Comment by mooreds** [comment]
I plan to ask @synedra to review it tomorrow morning first, then ask for your blessing @lyleschemmerling , because of the GH action change (which is minor).

**Comment by LucasPMorris** [comment]
Replying from email, not GH or whatever. In a restaurant in HA and this
raised some questions in my head so replying via the avenue in front of me.

What was the intent of adding support as a reviewer? With 100+ file changes
I don't think anyone in support can properly review (and appropriately
approve) these changes.

**Comment by mooreds** [comment]
@LucasPMorris go back to your vacation! :) 

Seriously, I didn't pick the reviewers; it happens automatically. It happens because of a change to codeowners ( https://github.com/FusionAuth/fusionauth-site/commit/d347d1a4d35f737fb4e814ccd9d727bb68e9126b ). 

I don't know what drove that change, wasn't involved.

**Comment by LucasPMorris** [comment]
Haha, okay, going back on vacation.

I just didn't want someone on the support team  to either 1) give blanket
approval for a significant change or 2) become immediately overwhelmed with
reviewing 100+ file changes.

Thanks,
Luke

**Review by lyleschemmerling — APPROVED** [review]

**Review by synedra — APPROVED** [review]
It's clear and I'm excited to have a new tool to make our content more consistent!

**Pull request merged**
