### PR TITLE
Session management blog post

### PR DESCRIPTION
**Pull request by mooreds**
Todo:

* seo review
* new image

### CODE REVIEW

**Review by mark-robustelli — APPROVED** [review]
Just a few suggestions and if you don't like them I approved to go out.  If you change and need approval again, just let me know.

**Comment by mark-robustelli** [comment]
Also, it seems the header image here almost seems like an ad vs our normal header images.

**Comment by mooreds** [comment]
Thanks @mark-robustelli . I need to request a new header image, but wanted to get devrel review before doing so.

**Review by bradmccarty — APPROVED** [review]
LGTM

**Comment by mooreds** [comment]
Thanks @bradmccarty .

@mark-robustelli I will ask for one more review when I get the header image back, so that I can then publish/merge it.

**Review by mark-robustelli — APPROVED** [review]
LGTM

**Pull request merged**
