### PR TITLE
:construction: Adding `vale` for text linting

### PR DESCRIPTION
**Pull request by vcampitelli**
After an initial attempt at #200, I'm trying to add [`vale`](https://vale.sh/docs/) again.

## Introduction

> Vale is a command-line tool that brings code-like linting to prose. It's [fast](https://gitlab.com/jdkato/vale#mag-at-a-glance-vale-vs-), cross-platform (Windows, macOS, and Linux), and highly customizable.

&mdash; [`jdkato/vale`](https://gitlab.com/jdkato/vale)

## Errors

There are still a lot of errors that vale caught (_4278 errors in 1277 files_ right now), but it was I managed to fix a lot of them already, and as time was passing by and I needed to keep merging `master` and fixing conflicts, I decided to stop and open the PR.

## Reviewing

To review this, please take a look at the configuration at `.vale.ini` and `.github/vale/styles` and some changes that I made at `src/content`.

## Running

To test this locally, I recommend either:

- [Installing vale locally](https://vale.sh/docs/vale-cli/installation/) and running `vale --config .vale.ini astro/src/content/`
- Running via Docker:
    ```shell
    cd /path/to/fusionauth-site
    docker run --rm -v "$(pwd)/.vale.ini:/etc/.vale.ini" -v "$(pwd)/.github:/etc/.github" -v "$(pwd)/astro:/docs" -w /docs jdkato/vale --config /etc/.vale.ini src/content
    ```

## Workflow

The [GitHub workflow](https://github.com/FusionAuth/fusionauth-site/blob/c7798cd8ce9bb9ddb1336e6471fa6e357bc1825e/.github/workflows/vale.yml) only runs on added/modified lines and it's not blocking the PR.

## Known Words

I know we have a [`knownwords.txt`](https://github.com/FusionAuth/fusionauth-site/blob/master/.github/knownwords.txt) already, but it has a lot of errors (e.g. all spelling variations of "FusionAuth"), so it defeats the purpose of having a consistent writing style.

I spent a lot of time trying to remove those duplicates, but decided to revert everything at d50db59d8f8bdcb508aa0f98bebe499a671691e4 and keep only the words that I manually added to [`.github/vale/styles/config/vocabularies/FusionAuth/accept.txt`](https://github.com/FusionAuth/fusionauth-site/blob/e135669aa7923882599581c9029017f5e054f5be/.github/vale/styles/config/vocabularies/FusionAuth/accept.txt).

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1205092803523169

### CODE REVIEW

**Comment by vcampitelli** [comment]
I've rebased the branch and fixed conflicts.

**Comment by vcampitelli** [comment]
I've merged and fixed conflicts again. I also updated the description with a lot more details.

**Review by mooreds — COMMENTED** [review]
> I know we have a knownwords.txt already, but it has a lot of errors (e.g. all spelling variations of "FusionAuth"), so it defeats the purpose of having a consistent writing style.

That's because sometimes `fusionauth` refers to a directory and other times `FusionAuth` refers to the product.

Should we document how to respond to vale feedback in DocsDevREADME? Some of it is actionable (fixing duplicate words for sure). What do I do as a dev if I'm getting feedback that I know isn't actionable (I really need to use the passive voice for some reason)?

**Comment by vcampitelli** [comment]
@mooreds I've added a section to `DocsDevREADME`, ignored some Astro components, and also fixed a few more errors.

**Review by mooreds — APPROVED** [review]
LGTM, thanks for adding that guidance.

**Pull request merged**
