### PR TITLE
Feature page connectors

### PR DESCRIPTION
**Pull request by mooreds**
Adds the connector feature page.

### CODE REVIEW

**Review by voidmain — COMMENTED** [review]
Made a few changes directly in the code. Mainly fixing HTML a bit and fixing the YouTube URL for the button.

**Comment by mooreds** [comment]
@voidmain I'll add the arrows to the other feature pages.

**Comment by voidmain** [comment]
Sounds good. I added those specifically here since the links were white. At least on the other pages they are blue. 😁

**Comment by voidmain** [comment]
I squash merged this manually since the conflict was simple to fix on the CLI. It looks like Github doesn't figure that out. I'll just close this PR since it is in master.

**Pull request closed without merging**
