### PR TITLE
Update doc nav to handle order

### PR DESCRIPTION
**Pull request by mooreds**
Don't forget to update wiki/Readme doc about topOfNav when this is merged

### CODE REVIEW

**Review by lyleschemmerling — DISMISSED** [review]
I'm concerned that this will be difficult to maintain, but I couldn't think of a better way to do it. I even gave chat gpt a shot and it came up with something similar to what you did here, so go for it.

**Comment by mooreds** [comment]
beep boop.

Will merge and fix conflicts and then ask for a cursory re-review.

**Comment by lyleschemmerling** [comment]
you're not allowed to beep boop. You are a Human Dan, not a Robot Dan

**Comment by mooreds** [comment]
im-only-human-after-all

**Comment by mooreds** [comment]
im-only-human-after-all

**Review by lyleschemmerling — APPROVED** [review]

**Pull request merged**
