### PR TITLE
Update passwordless guide images

### PR DESCRIPTION
**Pull request by mooreds**
Updated these to conform to our style guide standards.

### CODE REVIEW

**Review by robotdan — COMMENTED** [review]
The `localization-screen-for-email-template.png` screenshot doesn't look correct, I was unable to recreate on demo, but it looks like some JavaScript is failing. The lower text area should not be there.

**Comment by mooreds** [comment]
I was also unable to recreate. Just re-took the screenshot and it looks normal now.

**Comment by robotdan** [comment]
Looks good!

**Review by robotdan — COMMENTED** [review]
LGTM

**Pull request merged**
