### PR TITLE
Reviewing Python Flask quickstart (Astro)

### LINKED ISSUE #2241: Review Python Flask quickstart (Astro)
Reviewing and improving the new Python Flask quickstart (`/quickstarts/quickstart-python-flask-web`)

### PR DESCRIPTION
**Pull request by vcampitelli**
Closes #2241 

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1205101483756024

### CODE REVIEW

**Comment by vcampitelli** [comment]
@mooreds I have fixed some typos, added some periods to lists, some `backticks` in filenames and changed the "Repository Contents" section from a table to a list, as the table was breaking words in new lines and it was strange.

I think I should also fix long lines that were split as we do in our current docs, is that ok?

**Comment by mooreds** [comment]
> I think I should also fix long lines that were split as we do in our current docs, is that ok?

Sure.

Please have this PR opened against `development` rather than master. (see https://github.com/FusionAuth/fusionauth-site/pull/2240).

**Comment by vcampitelli** [comment]
@mooreds Changed branch to `development` and joined long lines.

**Comment by mooreds** [comment]
@vcampitelli do we need to do anything here?

**Comment by vcampitelli** [comment]
@mooreds I had to redo my changes due to the original quickstart being rewritten. Now we just need to review and merge.

**Pull request merged**
