### PR TITLE
Added per month to pricing page.

### PR DESCRIPTION
**Pull request by mooreds**
Screen Shot 2021-05-24 at 8 50 48 AM
This was confusing to at least one person: https://twitter.com/mickeymond/status/1396713403943735298 so wanted to make it crystal clear.

### CODE REVIEW

**Comment by voidmain** [comment]
That's a little crowded. Let me try something on this branch.

**Comment by voidmain** [comment]
Screen Shot 2021-05-24 at 9 05 42 AM

**Comment by voidmain** [comment]
I could also make the `/mo` say `/month` and make it smaller text.

**Comment by mooreds** [comment]
@voidmain I think that the `/mo` makes it clear enough.

**Comment by voidmain** [comment]
Pushed those changes.

**Comment by mooreds** [comment]
Gets a teensy bit crowded when you are at max pricing for enterprise (see image). How hard would it be to make `/mo` smaller?

Screen Shot 2021-05-24 at 9 38 57 AM

**Pull request merged**
