### PR TITLE
Update cloud installation guide

### PR DESCRIPTION
**Pull request by mooreds**
This does a couple of things.

1. Updates the cloud install guide with the new workflows and screen captures from the new account.fusionauth.io
2. Broke out a separate 'account portal' doc which is an overview of all the account portal actions, which is not specific to the cloud install process.

### CODE REVIEW

**Review by robotdan — COMMENTED** [review]
Are the login screens, such as `registration-second-screen.png` using a different dimension or screenshot strategy?

**Comment by mooreds** [comment]
All screenshots were captured with the fa-screenshot tool on my macbook's screen. Dimensions should be automatic.

**Review by troutgirlfusionauth — CHANGES_REQUESTED** [review]
* Missing image "The support tab"

* In the Custom FusionAuth Cloud features section, it says "open a contact us"

* Long links wrap distractingly (optional)

**Comment by mooreds** [comment]
Merging after fixes from Joyce.

**Pull request merged**
