### PR TITLE
Fix advanced reg form guide

### PR DESCRIPTION
**Pull request by mooreds**
Fixed images, added a new one.

### CODE REVIEW

**Comment by robotdan** [comment]
Is this one on hold? 

A couple of notes, the screenshots don't look to be the correct dimensions, and scroll bars are enabled.

**Comment by mooreds** [comment]
Yes, I redid the images and they still had issues. I think I've fixed all of them (you told me how to turn off the scrollbars and I just have to take the screenshots on the mac, not my monitor), just haven't redone them yet. 

I wasn't sure if there were changes needed with the admin forms for the 1.20 release. I believe we decided I'd update the guide, correct?

**Comment by robotdan** [comment]
> I wasn't sure if there were changes needed with the admin forms for the 1.20 release. I believe we decided I'd update the guide, correct?



Yes, if that still works for you. If not, I can do it.

**Comment by mooreds** [comment]
Fixed the images first. Will update the guide with new functionality next.

**Comment by mooreds** [comment]
Next being a separate PR.

**Review by robotdan — COMMENTED** [review]
Looks good. 

The `flask-app-screen-shot.png` screenshot looks like it may still have dark mode on (the address bar is dark), but not a big deal. Maybe just leave a note in the adoc file that it could use an update in the future.

**Comment by mooreds** [comment]
Ah, thanks. I think it might have been in incognito mode. Will leave a note.

**Pull request merged**
