### PR TITLE
blog: Family API 

### PR DESCRIPTION
**Pull request by sixhobbits**

### CODE REVIEW

**Review by ColinFrick — CHANGES_REQUESTED** [review]

**Comment by ColinFrick** [comment]
@sixhobbits Thanks for the changes.

Regarding the permission check in `change-consent-status`, `res.send` does not exit the function, so anything after that will still be executed, and the consent status changed.

Could you update the example repo?

**Comment by rideam** [comment]
@ColinFrick I have pushed updates to fix the `change-consent-status` not exiting if role check fails, the example repo is also updated https://github.com/ritza-co/fusionauth-family-api-example

**Review by ColinFrick — APPROVED** [review]

**Comment by ColinFrick** [comment]
@mooreds LGTM, could you pull the example repo into the org so @rideam can update the PR?

**Comment by mooreds** [comment]
This is done: https://github.com/FusionAuth/fusionauth-example-family-api

**Comment by mooreds** [comment]
@rideam once you've updated the GH repo links, tag me and I'll take care of publishing this on the correct date. I also will want to add a 'related posts' section to the family and consents API pages to highlight this excellent blog post.

**Comment by rideam** [comment]
@mooreds I have updated the example links

**Comment by mooreds** [comment]
Closing under https://github.com/FusionAuth/fusionauth-site/pull/2243

**Pull request closed without merging**
