### PR TITLE
Added script to find keys close to expiry

### PR DESCRIPTION
**Pull request by mooreds**
Came out of a support conversation.

### CODE REVIEW

**Review by spwitt — CHANGES_REQUESTED** [review]
Do you think readers will know what `jq` is or be able to find it easily? It is the first result when Googling `jq`, so maybe it's fine.

**Comment by mooreds** [comment]
Hmmm, @spwitt . I added some text around the requirements and a pointer to the repo which has more full featured prereqs.

Does that suit or do you think we need more?

**Review by spwitt — APPROVED** [review]
Looks good. I didn't realize there was more info in the example scripts repo.

**Review by spwitt — APPROVED** [review]
Looks good. I didn't realize there was more info in the example scripts repo.

**Pull request merged**
