### PR TITLE
feat(DocsDevREADME): extend with Video/Audio Recording Guide

### PR DESCRIPTION
**Pull request by escii**
Guidelines regarding "Audio/Video Recording" and "Recording Software", also "Open questions" (this may need to be removed).

### CODE REVIEW

**Comment by mooreds** [comment]
@alex-fusionauth would love your thoughts on this.

**Comment by alex-fusionauth** [comment]
> @alex-fusionauth would love your thoughts on this.

I think this is a good start, I have continued with a new PR for updates on the main repo #2470

**Comment by Aaron-Ritter** [comment]
Addresses https://github.com/FusionAuth/fusionauth-site/pull/2377

**Comment by Aaron-Ritter** [comment]
Addresses: https://github.com/FusionAuth/fusionauth-issues/issues/2256

**Comment by Aaron-Ritter** [comment]
closing, new version is developed under https://github.com/FusionAuth/fusionauth-site/pull/2470

**Pull request closed without merging**
